name: tf_training
channels:
  - defaults
dependencies:
  - _tflow_select==2.3.0
  - absl-py==0.7.1
  - astor==0.7.1
  - backcall==0.1.0
  - blas==1.0
  - c-ares==1.15.0
  - ca-certificates==2019.1.23
  - certifi==2019.3.9
  - cycler==0.10.0
  - dbus==1.13.6
  - decorator==4.4.0
  - expat==2.2.6
  - fontconfig==2.13.0
  - freetype==2.9.1
  - gast==0.2.2
  - glib==2.56.2
  - grpcio==1.16.1
  - gst-plugins-base==1.14.0
  - gstreamer==1.14.0
  - h5py==2.9.0
  - hdf5==1.10.4
  - icu==58.2
  - intel-openmp==2019.3
  - ipykernel==5.1.0
  - ipython==7.5.0
  - ipython_genutils==0.2.0
  - jedi==0.13.3
  - jpeg==9b
  - jupyter_client==5.2.4
  - jupyter_core==4.4.0
  - keras==2.2.4
  - keras-applications==1.0.7
  - keras-base==2.2.4
  - keras-preprocessing==1.0.9
  - kiwisolver==1.1.0
  - libedit==3.1.20181209
  - libffi==3.2.1
  - libgcc-ng==8.2.0
  - libgfortran-ng==7.3.0
  - libpng==1.6.37
  - libprotobuf==3.7.1
  - libsodium==1.0.16
  - libstdcxx-ng==8.2.0
  - libtiff==4.0.10
  - libuuid==1.0.3
  - libxcb==1.13
  - libxml2==2.9.9
  - markdown==3.1
  - matplotlib==3.0.3
  - mkl==2019.3
  - mkl_fft==1.0.12
  - mkl_random==1.0.2
  - mock==2.0.0
  - ncurses==6.1
  - numpy==1.16.3
  - numpy-base==1.16.3
  - olefile==0.46
  - openssl==1.1.1b
  - pandas==0.24.2
  - parso==0.4.0
  - patsy==0.5.1
  - pbr==5.1.3
  - pcre==8.43
  - pexpect==4.7.0
  - pickleshare==0.7.5
  - pillow==6.0.0
  - pip==19.1.1
  - prompt_toolkit==2.0.9
  - protobuf==3.7.1
  - ptyprocess==0.6.0
  - pygments==2.4.0
  - pyparsing==2.4.0
  - pyqt==5.9.2
  - python==3.7.3
  - python-dateutil==2.8.0
  - pytz==2019.1
  - pyyaml==5.1
  - pyzmq==18.0.0
  - qt==5.9.7
  - readline==7.0
  - scikit-learn==0.20.3
  - scipy==1.2.1
  - seaborn==0.9.0
  - setuptools==41.0.1
  - sip==4.19.8
  - six==1.12.0
  - sqlite==3.28.0
  - statsmodels==0.9.0
  - tensorboard==1.13.1
  - tensorflow==1.13.1
  - tensorflow-base==1.13.1
  - tensorflow-estimator==1.13.0
  - termcolor==1.1.0
  - tk==8.6.8
  - tornado==6.0.2
  - tqdm==4.31.1
  - traitlets==4.3.2
  - wcwidth==0.1.7
  - werkzeug==0.15.2
  - wheel==0.33.2
  - xz==5.2.4
  - yaml==0.1.7
  - zeromq==4.3.1
  - zlib==1.2.11
  - zstd==1.3.7
  - pip: 
    - joblib==0.13.2
    - opencv-python==4.1.0.25
    - pygal==2.4.0
    - scikit-plot==0.3.7